# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Database.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1058, 754)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_Q3_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Q3_3.setGeometry(QtCore.QRect(10, 140, 1021, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.groupBox_Q3_3.setFont(font)
        self.groupBox_Q3_3.setObjectName("groupBox_Q3_3")
        self.lineEdit_Query = QtWidgets.QLineEdit(self.groupBox_Q3_3)
        self.lineEdit_Query.setGeometry(QtCore.QRect(10, 30, 901, 51))
        self.lineEdit_Query.setText("")
        self.lineEdit_Query.setObjectName("lineEdit_Query")
        self.Button_Query = QtWidgets.QPushButton(self.groupBox_Q3_3)
        self.Button_Query.setGeometry(QtCore.QRect(920, 30, 91, 51))
        self.Button_Query.setObjectName("Button_Query")
        self.groupBox_Q3_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Q3_2.setGeometry(QtCore.QRect(10, 20, 1021, 111))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.groupBox_Q3_2.setFont(font)
        self.groupBox_Q3_2.setObjectName("groupBox_Q3_2")
        self.label_Button = QtWidgets.QLabel(self.groupBox_Q3_2)
        self.label_Button.setGeometry(QtCore.QRect(10, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_Button.setFont(font)
        self.label_Button.setObjectName("label_Button")
        self.comboBox_Button = QtWidgets.QComboBox(self.groupBox_Q3_2)
        self.comboBox_Button.setGeometry(QtCore.QRect(170, 20, 431, 31))
        self.comboBox_Button.setCurrentText("")
        self.comboBox_Button.setObjectName("comboBox_Button")
        self.Button_ButtonQuery = QtWidgets.QPushButton(self.groupBox_Q3_2)
        self.Button_ButtonQuery.setGeometry(QtCore.QRect(610, 20, 111, 31))
        self.Button_ButtonQuery.setObjectName("Button_ButtonQuery")
        self.lineEdit_ButtonQuery = QtWidgets.QLineEdit(self.groupBox_Q3_2)
        self.lineEdit_ButtonQuery.setGeometry(QtCore.QRect(10, 60, 1001, 41))
        self.lineEdit_ButtonQuery.setText("")
        self.lineEdit_ButtonQuery.setObjectName("lineEdit_ButtonQuery")
        self.groupBox_Q3_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Q3_4.setGeometry(QtCore.QRect(20, 260, 1021, 451))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.groupBox_Q3_4.setFont(font)
        self.groupBox_Q3_4.setObjectName("groupBox_Q3_4")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_Q3_4)
        self.scrollArea.setGeometry(QtCore.QRect(10, 30, 1001, 411))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 999, 409))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 1001, 411))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1058, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_Q3_3.setTitle(_translate("MainWindow", "Query"))
        self.Button_Query.setText(_translate("MainWindow", "Enter"))
        self.groupBox_Q3_2.setTitle(_translate("MainWindow", "Button"))
        self.label_Button.setText(_translate("MainWindow", "選擇資料庫功能："))
        self.Button_ButtonQuery.setText(_translate("MainWindow", "Enter"))
        self.groupBox_Q3_4.setTitle(_translate("MainWindow", "Result"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
